common/models/Partner.php
<?php

namespace common\models;

use common\components\mailer\Message;
use common\helpers\ActiveRecordHelper;
use common\jobs\BonusSetJob;
use common\jobs\planfix\PartnerJob;
use paulzi\jsonBehavior\JsonBehavior;
use paulzi\jsonBehavior\JsonField;
use paulzi\jsonBehavior\JsonValidator;
use phpDocumentor\Reflection\Types\Boolean;
use Yii;
use yii\db\Expression;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\helpers\Url;

/**
 * This is the model class for table "{{%partner}}".
 *
 * @property string $id
 * @property string $name
 * @property string $region_id
 * @property string $category_id
 * @property integer $status_id
 * @property string $contract_id
 * @property string $org_id
 * @property string $agency_id
 * @property integer $manager_client
 * @property integer $manager_development
 * @property string $api_token
 * @property integer $credit_limit
 * @property integer $samples_credit_limit
 * @property integer $credit_time
 * @property boolean $is_dealer
 * @property boolean $premium_brand_allowed
 * @property boolean $no_vat
 * @property string $created_at
 * @property string $updated_at
 * @property boolean $is_deleted
 * @property JsonField $params
 *
 * @property Contract $contractDefault
 * @property Contract[] $contracts
 * @property Company[] $companies
 * @property Region $region
 * @property PartnerCategory $category
 * @property Organization $defaultOrganization
 * @property Partner $agency
 * @property Manager $managerClient
 * @property Manager $managerDevelopment
 * @property Dealer $dealer
 * @property PartnerDiscount[] $discounts
 * @property PartnerSumPlan[] $planPoints
 * @property User[] $users
 * @property User $firstUser
 * @property Collection[] $publicCollections
 * @property Collection[] $oasisCollections
 * @property Collection[] $collections
 * @property User[] $chiefs
 * @property bool $isHasMarketingBonus
 * @property Order[] $orders
 * @property PartnerAddress[] $addresses
 *
 * @property int $genericCreditUsed
 * @property int $sampleCreditUsed
 * @property bool $isOasis
 * @property float $currentRedemption
 * @property float $freeDeliveryThresholdFactor
 * @property int|null $freeDeliverySum
 * @property PartnerSamplePreference $samplePreference
 * @property SampleBonus[] $sampleBonuses
 * @property SampleDistribution[] $sampleDistributions
 * @property bool $allowCredit
 * @property bool $isFreeDeliveryBonus
 * @property bool $isInPromotionLeague
 * @property bool $hasOwnProduction
 * @property bool $needToExcludeBranding
 * @property bool $forbiddenSeasonBranding
 * @property string $birthday
 */
class Partner extends \yii\db\ActiveRecord
{
    const STATUS_BUSINESS_PARTNER    = 1; // Бизнес-партнер
    const STATUS_DEALER              = 2; // Дилер
    const STATUS_DISTRIBUTOR         = 3; // Дистрибутор
    const STATUS_BUYER               = 4; // Покупатель
    const STATUS_PARTNER             = 5; // Партнер
    const STATUS_FEDERAL_DEALER      = 6; // Федеральный Дилер
    const STATUS_FEDERAL_DISTRIBUTOR = 7; // Федеральный Дистрибьютор
    const STATUS_ONLINE_SHOP         = 8; // Интернет магазин
    const STATUS_END_USER            = 9; // Конечный заказчик

    const PARTNER_OASIS = '000004557';

    private $_bonusCoupons = [];

    public $total;
    public $delay;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%partner}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class'      => JsonBehavior::class,
                'attributes' => ['params'],
                'emptyValue' => '{}',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'name'], 'required'],
            [['status_id', 'manager_client', 'manager_development', 'credit_limit', 'samples_credit_limit', 'credit_time'], 'integer'],
            [['is_dealer', 'premium_brand_allowed', 'no_vat', 'is_deleted'], 'boolean'],
            [['created_at', 'updated_at'], 'safe'],
            [['id', 'region_id', 'category_id', 'contract_id', 'org_id', 'agency_id'], 'string', 'max' => 9],
            [['name'], 'string', 'max' => 100],
            [['api_token'], 'string', 'max' => 40],
            [['params'], JsonValidator::class, 'merge' => true, 'on' => 'admin'],
            [['birthday'], 'date',
                'format'                   => 'php:d.m.Y',
                'timestampAttribute'       => 'birthday',
                'timestampAttributeFormat' => 'php:Y-m-d',
            ],
            [['birthday'], 'default', 'value' => null],
            [['params'], 'filter', 'filter' => function($value) {
                /** @var JsonField $value */
                $value['bonuses'] = !empty($value['bonuses']) ? array_values($value['bonuses']) : null;
                if (($value['fBonusesAmount'] ?? null) === '') {
                    unset($value['fBonusesAmount']);
                }
                $fBonuses = [];
                foreach ($value['fBonuses'] ?? [] as $k => $item) {
                    if ($item['allowed']) {
                        $fBonuses[$k] = $item;
                    }
                }
                if ($fBonuses) {
                    $value['fBonuses'] = $fBonuses;
                } else {
                    unset($value['fBonuses']);
                }
                return array_filter($value->toArray(), function($v) { return $v !== null; });
            }, 'on' => 'admin'],
        ];
    }

    /**
     * @inheritdoc
     * @throws \yii\base\InvalidConfigException
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        if (isset($changedAttributes['params'])) {
            $old = new JsonField($changedAttributes['params']);
            if (Json::encode($old['bonuses'] ?? null) !== Json::encode($this->params['bonuses'] ?? null)) {
                $set = [];
                foreach ($this->params['bonuses'] ?? [] as $bonus) {
                    if ($bonus['type'] === 'brand') {
                        $bonus['id'] = substr($bonus['id'], -5);
                    }
                    if (isset($bonus['value']) && is_numeric($bonus['value'])) {
                        $bonus['value'] = (float)$bonus['value'];
                    }
                    $set[] = $bonus;
                }

                $job = new BonusSetJob();
                $job->partnerId = $this->id;
                $job->set = $set;
                Yii::$app->queue->push($job);
            }
        }
    }

    /**
     * Основной договор
     * @return \yii\db\ActiveQuery
     */
    public function getContractDefault()
    {
        return $this->hasOne(Contract::className(), ['id' => 'contract_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContracts()
    {
        return $this->hasMany(Contract::className(), ['partner_id' => 'id'])
            ->with('company')
            ->orderBy(['is_credit' => SORT_DESC, 'name' => SORT_ASC])
            ->indexBy('id')
            ->inverseOf('partner');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompanies()
    {
        return $this->hasMany(Company::className(), ['id' => 'company_id'])
            ->viaTable('contract', ['partner_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRegion()
    {
        return $this->hasOne(Region::className(), ['id' => 'region_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(PartnerCategory::className(), ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDefaultOrganization()
    {
        return $this->hasOne(Organization::className(), ['id' => 'org_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgency()
    {
        return $this->hasOne(static::className(), ['id' => 'agency_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getManagerClient()
    {
        return $this->hasOne(Manager::className(), ['id' => 'manager_client']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getManagerDevelopment()
    {
        return $this->hasOne(Manager::className(), ['id' => 'manager_development']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDealer()
    {
        return $this->hasOne(Dealer::className(), ['partner_id' => 'id'])
            ->inverseOf('partner');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDiscounts()
    {
        return $this->hasMany(PartnerDiscount::className(), ['partner_id' => 'id'])
            ->indexBy('discount_id')
            ->inverseOf('partner');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanPoints()
    {
        return $this->hasMany(PartnerSumPlan::className(), ['partner_id' => 'id'])
            ->indexBy('date')
            ->inverseOf('partner');
    }

    /**
     * Пользователи партнёра
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::className(), ['partner_id' => 'id'])
            ->orderBy(['first_name' => SORT_ASC, 'last_name' => SORT_ASC])
            ->indexBy('id');
    }

    /**
     * Первый пользователь партнёра
     * @return \yii\db\ActiveQuery
     */
    public function getFirstUser()
    {
        return $this->hasOne(User::className(), ['partner_id' => 'id'])
            ->orderBy(['first_name' => SORT_ASC, 'last_name' => SORT_ASC])
            ->indexBy('id');
    }

    /**
     * Руководители партнёра (только для связок), для получения руководителей используй getChief()
     * @return \yii\db\ActiveQuery
     */

controllers/PartnerController.php
<?php

namespace oasis\controllers;

use common\components\ArrayDataProvider;
use common\models\App;
use common\models\Partner;
use common\models\PartnerCategory;
use common\models\StatVisit;
use oasis\models\forms\UserForm;
use Yii;
use yii\data\SqlDataProvider;
use yii\db\Expression;
use yii\helpers\Html;
use yii\web\NotFoundHttpException;
use common\components\Controller;
use common\jobs\UserCreateJob;
use common\widgets\Alert;
use common\models\User;
use oasis\actions\NotificationSettingsAction;
use yii\web\UploadedFile;
use yii\data\ActiveDataProvider;

class PartnerController extends Controller
{

    public $layout = 'cabinet';


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => 'yii\filters\AccessControl',
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['manager'],
                        'actions' => ['profile'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['manager'],
                    ],
                ],
            ],
            [
                'class' => 'yii\filters\VerbFilter',
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }


    /**
     * Список Контрагентов менеджера
     *
     * @return string
     */
    public function actionCounterParties()
    {
        $form = new UserForm();
        $form->load(Yii::$app->request->post());
        $partners = Partner::find(false, 'p')
            ->allowed(null, true)
            ->select(
                [
                    'id' => 'p.id',
                    'name' => 'p.name',
                    'manager_development' => 'manager_development.name',
                    'manager_client' => 'manager_client.name',
                    'status' => 'category.name',
                ]
            )
            ->leftJoin(['manager_development' => 'manager'], "p.manager_development = manager_development.id")
            ->leftJoin(['manager_client' => 'manager'], "p.manager_client = manager_client.id")
            ->leftJoin(['category' => 'partner_category'], "category.id = p.category_id");
        if ($form->fio) {
            $partners->andFilterWhere(
                [
                    'or',
                    ['ilike', 'p.name', $form->fio],
                ]
            );
        }

        $models = new ArrayDataProvider(
            [
                'allModels' => $partners->asArray()->all(),
                'pagination' => [
                    'pageSize' => 100,
                ],
                'sort' => [
                    'attributes' => ['id', 'name', 'manager_development', 'manager_client', 'status'],
                ],
            ]
        );

        return $this->render(
            'index',
            [
                'dataProvider' => $models,
                'form' => $form,
            ]
        );
    }

    /**
     * Редактировать профиль
     *
     * @param null $id
     *
     * @return array|string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionProfile($id = null)
    {
        $partner = Partner::find(false, 'p')
            ->select(
                [
                    '*',

                ]
            )
            ->where('id = :id', [':id' => $id])->one();
        if ($partner->load(Yii::$app->request->post())) {
            if ($partner->save()) {
                return $this->flash('Изменения сохранены', Alert::TYPE_SUCCESS);
            } elseif (Yii::$app->request->isAjax) {
                return $this->flash(Html::errorSummary($partner, ['header' => '']), Alert::TYPE_DANGER);
            }
        }

        return $this->render(
            'profile',
            [
                'partner' => $partner,
            ]
        );
    }

}

views/partner/index.php
<?php
/**
 * @var $this yii\web\View
 * @var \yii\data\ActiveDataProvider $dataProvider
 * @var \common\models\User[] $models
 */

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Контрагенты';

$currentUserId = Yii::$app->user->identity->id;
$colors = [
    '#456385', '#9471db', '#6ad19f', '#4d71db', '#8cbb2d', '#db94db', '#ff7194', '#4d94db', '#db4d4d', '#71b84d',
    '#ff944d', '#4d71db', '#ff944d', '#4db8db', 'Coral', 'Crimson', 'Tomato', 'OliveDrab', 'brown', 'cadetblue',
    'darkcyan', 'steelblue', 'seagreen', 'rebeccapurple',
];
?>


<div class="page page-employee-list">

    <h1 class="page__heading"><?= $this->title ?></h1>


    <div class="page-employee-list__top-container">

        <?php /* Поиск */ ?>
        <form class="page-employee-list__filter" action="<?= Url::current() ?>" method="POST">
            <?= Html::hiddenInput(Yii::$app->request->csrfParam, Yii::$app->request->csrfToken) ?>
            <?= Html::activeTextInput($form, 'fio', [
                'placeholder' => 'Поиск по имени контрагента',
            ]); ?>
        </form>

    </div>


    <?php /* Список сотрудников */ ?>
    <div class="page-employee-list__body">
        <?= Html::beginTag('div', [
            'class' => 'employee-list js--mass',
            'data' => [
                'mass' => [
                    'id' => '_employee-list',
                ],
            ],
        ]) ?>

        <?php /* Хэдер списка с переключателями сортировки */ ?>
        <header class="employee-list__header">

            <div class="employee-list__header-inner-wrapper">

                <?php /* Имя и должность */ ?>
                <div class="employee-list__header-cell employee-list__header-cell_name-and-post">
                    <?php $turn = $dataProvider->sort->getAttributeOrder('name'); ?>
                    <?= Html::a('Контрагент', $dataProvider->sort->createUrl('name'), [
                        'class' => [
                            'sort-toggler',
                            $turn ? 'active' : null,
                            $turn === SORT_DESC ? 'reverse' : null,
                        ],
                    ]) ?>
                </div>

                <?php /* Менеджер по ведению */ ?>
                <div class="employee-list__header-cell employee-list__header-cell_email">
                    <?php $turn = $dataProvider->sort->getAttributeOrder('manager_client'); ?>
                    <?= Html::a('Менеджер по ведению', $dataProvider->sort->createUrl('manager_client'), [
                        'class' => [
                            'sort-toggler',
                            $turn ? 'active' : null,
                            $turn === SORT_DESC ? 'reverse' : null,
                        ],
                    ]) ?>
                </div>


                <?php /* Менеджер по развитию */ ?>
                <div class="employee-list__header-cell employee-list__header-cell_email">
                    <?php $turn = $dataProvider->sort->getAttributeOrder('manager_development'); ?>
                    <?= Html::a('Менеджер по развитию', $dataProvider->sort->createUrl('manager_development'), [
                        'class' => [
                            'sort-toggler',
                            $turn ? 'active' : null,
                            $turn === SORT_DESC ? 'reverse' : null,
                        ],
                    ]) ?>
                </div>

            </div>

        </header>


        <?php /* Список контрагентов менеджера */ ?>
        <div class="employee-list__body">

            <?php foreach ($dataProvider->models as $key => $model): ?>
                <div class="employee-list__row mass-item" id="employee-list-<?= $key ?>">

                    <div class="employee-list__row-wrapper employee-list__row-wrapper_left">

                        <?php /* Кнопка-раскрывашка информации пользователя в мобильной версии */ ?>
                        <?= Html::button('', [
                            'class' => 'employee-list__toggler js--toggle-class',
                            'data' => [
                                'toggle-class' => [
                                    'target' => '.employee-list__row <<',
                                ],
                            ],
                        ]) ?>


                        <?php /* Аватар */ ?>
                        <div class="employee-list__cell employee-list__cell_image">
                            <a class="employee-list__image-link" href="<?= Url::to(['/user/profile', 'id' => $model['id']]) ?>">
                                    <span class="employee-list__image employee-list__image_empty" style="background-color: <?= $colors[crc32($model['id']) % count($colors)] ?>;">
                                            <?= mb_substr($model['name'], 0, 1, 'utf8') . mb_substr($model['name'], 0, 1, 'utf8') ?>
                                        </span>
                            </a>
                        </div>


                        <?php /* Имя и должность */ ?>
                        <div class="employee-list__cell employee-list__cell_name-and-post">
                            <a class="employee-list__name" href="<?= Url::to(['/partner/profile', 'id' =>$model['id']]) ?>"><?= $model['name'] ?></a>
                            <span class="employee-list__post"><?= $model['status'] ?></span>
                        </div>

                    </div>


                    <?php /* Блок с этой информацией переключается в мобильной версии */ ?>
                    <div class="employee-list__row-wrapper employee-list__row-wrapper_right">

                        <?php /* Менеджер по ведению */ ?>
                        <div class="employee-list__cell employee-list__cell_access-level">
                            <span class="employee-list__cell-title">Менеджер по ведению</span>
                            <span class="employee-list__access-level employee-list__cell-text"><?= $model['manager_development'] ?></span>
                        </div>


                        <?php /* Менеджер по развитию */ ?>
                        <div class="employee-list__cell employee-list__cell_access-level">
                            <span class="employee-list__cell-title">Менеджер по ведению</span>
                            <span class="employee-list__access-level employee-list__cell-text"><?= $model['manager_client'] ?></span>
                        </div>


                        <?php /* Кнопка перехода в профиль сотрудника (мобильная версия) */ ?>
                        <a class="btn2 employee-list__profile-link btn2_color_default btn2_full-width" href="<?= Url::to(['/user/update', 'id' => $model['id']]) ?>">
                                <span class="btn2__wrapper">
                                    <span class="btn2__text">Редактировать</span>
                                </span>
                        </a>

                    </div>

                </div>
            <?php endforeach; ?>

        </div>

        <?= Html::endTag('div') ?>
    </div>


    <?php /* Пагинация */ ?>
    <div class="page-employee-list__pagination">
        <?= \yii\widgets\LinkPager::widget(
            [
                'options' => [
                    'tag' => 'div',
                    'class' => 'pagination',
                ],
                'activePageCssClass' => 'pagination__item_active',
                'linkContainerOptions' => [
                    'tag' => 'div',
                    'class' => 'pagination__item',
                ],
                'linkOptions' => [
                    'class' => 'pagination__btn',
                ],
                'disabledPageCssClass' => 'pagination__item_disabled',
                'disabledListItemSubTagOptions' => [
                    'tag' => 'button',
                    'class' => 'pagination__btn',
                    'type' => 'button',
                    'disabled' => true,
                ],
                'maxButtonCount' => 5,
                'nextPageCssClass' => 'pagination__next',
                'prevPageCssClass' => 'pagination__prev',
                'pagination' => $dataProvider->pagination,
            ]
        ) ?>
    </div>

</div>

views/partner/profile.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use common\models\User;
use common\widgets\formField\FormField;

/**
 * @var \yii\web\View $this
 * @var \common\models\User $user
 * @var array $notifications
 * @var array  $partner
 */

$this->title = 'Настройки';
?>
<div class="page page-profile">
    <h1 class="page__heading"><?= $this->title ?></h1>
    <div class="page-profile__mainbody">
        <div class="page__panel page__panel_with-border">
            <div class="tabs2 tabs2_theme_modern js--tabs2">
                <?php /* вкладоки десктоп + контент вкладок */ ?>
                <div class="page-profile__content-wrapper">
                    <?php /* десктоп вкладки */ ?>
                    <?php /* контент вкладок */ ?>
                    <div class="tabs2__content">
                        <?php /* Вкладка «Основные» */ ?>
                        <button class="btn2 btn2_color_default btn2_full-width-mobile"
                                name="action"
                                value="submit,noBrandingOneWarehouse"
                                form="cart_cart"
                        >
                        <span class="btn2__wrapper">
                            <span class="btn2__text">  <a class="menu__link" <?= Html::a('Назад', Yii::$app->request->referrer)?>
                                </a></span>
                        </span>
                        </button>
                        <div class="tabs2__tab tabs2__tab_active" id="general">
                            <form class="page-profile__general" action="<?= Url::current() ?>" method="post" data-via="ajax">
                                <?= Html::hiddenInput(Yii::$app->request->csrfParam, Yii::$app->request->csrfToken) ?>
                                <div class="page-profile__general-body">
                                    <?php $field = FormField::field($partner, 'birthday'); ?>
                                        <div class="textfield textfield_addon-before-nobg">
                                            <div class="textfield__wrapper">
                                                <div class="textfield__addon textfield__addon_before">
                                                    <span class="textfield__addon-icon oasisicon-calendar"></span>
                                                </div>
                                                <?= Html::activeTextInput($partner, 'birthday', [
                                                    'noStyle' => true,
                                                    'class'   => 'textfield__control js--datepicker',
                                                    'id'      => $field->id,
                                                    'value'   => $partner->birthday ? Yii::$app->formatter->asDate($partner->birthday, 'php:Y-m-d') : null,
                                                ]) ?>
                                            </div>
                                        </div>
                                    <?= $field->run() ?>
                                </div>
                                <footer class="page-profile__general-footer">
                                    <button class="btn2 btn2_color_success btn2_full-width-mobile">
                                        <span class="btn2__wrapper">
                                            <span class="btn2__text">Сохранить</span>
                                        </span>
                                    </button>
                                </footer>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>